import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - LightMove",
  description: "LightMove Privacy Policy. LightMove does not collect, transmit, or store any personal information. All data is stored locally on your device.",
  alternates: { canonical: "https://baitengfei.com/lightmove/privacy" },
  openGraph: {
    type: "website",
    url: "https://baitengfei.com/lightmove/privacy",
    title: "Privacy Policy - LightMove | 白腾飞",
    description: "LightMove Privacy Policy. LightMove does not collect, transmit, or store any personal information.",
  },
};

export default function LightMovePrivacyPage() {
  return (
    <main className="max-w-[700px] mx-auto py-10 px-4">
      {/* English Version */}
      <article>
        <h1 className="text-3xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-gray-500 text-sm mb-8">Last updated: March 2025</p>

        <p>
          LightMove is committed to protecting your privacy. This Privacy Policy explains how we handle
          information when you use our app.
        </p>

        <h2>1. Information We Collect</h2>
        <p>
          LightMove does not collect, transmit, or store any personal information on external servers.
          All data generated by your use of the App — including workout records, exercise counts, timers,
          and body weight logs — is stored locally on your device.
        </p>

        <h2>2. Sensor Usage</h2>
        <p>The App uses your device built-in sensors to provide its core functionality:</p>
        <ul>
          <li>Proximity Sensor — used to automatically detect push-up and plank movements.</li>
          <li>Motion Sensor (Accelerometer / Gyroscope) — used to automatically count squat repetitions.</li>
        </ul>
        <p>Sensor data is processed in real time on your device and is never stored or transmitted.</p>

        <h2>3. Data Storage</h2>
        <p>
          All workout data (exercise history, personal bests, body weight records) is saved locally on
          your device using Apple standard storage. This data is not accessible to us and is not shared
          with any third party.
        </p>

        <h2>4. Third-Party Services</h2>
        <p>
          LightMove does not integrate any third-party analytics, advertising SDKs, or tracking tools.
          We do not share your data with any third parties.
        </p>

        <h2>5. Children Privacy</h2>
        <p>
          LightMove does not knowingly collect personal information from children under 13. Since no
          data is collected or transmitted, the App is safe for users of all ages.
        </p>

        <h2>6. Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy from time to time. Any changes will be reflected by updating
          the &quot;Last updated&quot; date at the top of this page. Continued use of the App after changes
          constitutes acceptance of the updated policy.
        </p>

        <h2>7. Contact Us</h2>
        <p>
          If you have any questions about this Privacy Policy, please contact us at:{" "}
          <a href="https://baitengfei.com" className="underline text-gray-700">
            baitengfei.com
          </a>
        </p>
      </article>

      {/* Divider */}
      <hr className="my-12 border-t border-gray-300" />

      {/* Chinese Version */}
      <article>
        <h1 className="text-3xl font-bold mb-2">隐私政策</h1>
        <p className="text-gray-500 text-sm mb-8">最后更新：2025 年 3 月</p>

        <p>
          LightMove 重视您的隐私保护。本隐私政策说明了您在使用本应用时，我们如何处理相关信息。
        </p>

        <h2>1. 信息收集</h2>
        <p>
          本应用不会收集、传输或在外部服务器存储任何个人信息。您使用本应用产生的所有数据——包括训练记录、动作计数、计时数据及体重记录——均保存在您的设备本地。
        </p>

        <h2>2. 传感器使用</h2>
        <p>本应用使用设备内置传感器实现核心功能：</p>
        <ul>
          <li>接近传感器 — 用于自动识别俯卧撑和平板支撑动作。</li>
          <li>动作传感器（加速度计 / 陀螺仪）— 用于自动计数深蹲次数。</li>
        </ul>
        <p>传感器数据仅在设备本地实时处理，不会被存储或传输至任何外部服务器。</p>

        <h2>3. 数据存储</h2>
        <p>
          所有训练数据（运动历史、个人最佳记录、体重记录）均使用 Apple 标准存储方式保存在您的设备本地。我们无法访问这些数据，也不会与任何第三方共享。
        </p>

        <h2>4. 第三方服务</h2>
        <p>
          本应用未集成任何第三方数据分析、广告 SDK 或追踪工具。我们不会向任何第三方共享您的数据。
        </p>

        <h2>5. 儿童隐私</h2>
        <p>
          本应用不会主动收集 13 岁以下儿童的个人信息。由于本应用不收集或传输任何数据，适合所有年龄段用户使用。
        </p>

        <h2>6. 政策更新</h2>
        <p>
          我们可能会不定期更新本隐私政策。如有更新，将通过修改页面顶部的"最后更新"日期予以说明。在更新后继续使用本应用，即视为接受更新后的政策。
        </p>

        <h2>7. 联系我们</h2>
        <p>
          如您对本隐私政策有任何疑问，请通过以下方式联系我们：{" "}
          <a href="https://baitengfei.com" className="underline text-gray-700">
            baitengfei.com
          </a>
        </p>
      </article>
    </main>
  );
}
